a = float(input("First number: ")) 
b = float(input("Second number: ")) 
print("Sum:", a + b) 
print("Product:", a * b) 
try: print("Division:", a / b) 
  except ZeroDivisionError: print("Cannot divide by zero")
